reach4help/reach4help

.eslintrc-ts.js
.eslintrc.js
package.json
site/.eslintrc.js
site/src/pages/index.js
site/src/sections/Landing.js
web-client/.eslintrc.js

As we start introducing new sub-projects and sub-packages, we don't want to have completely independent / vastly-different configs for eslint... this PR unifies them into central "base" configs for js and ts, and then extends those.
I also ran `lint --fix` in `site`
We probably want to do the same thing for the prettier config

feat(unify-eslint-config): Unify eslint config across monorepo

---

CONTRIBUTING.md
api/CONTRIBUTING.md
site/CONTRIBUTING.md
web-client/CONTRIBUTING.md

This PR modifies the contributor guidelines so that people report security issues by mail and other issues via the github issue tracker.
Fixes #109

docs: change contrib guidelines for security issues

---

map/src/App.tsx
map/src/components/map.tsx

Too much zooming makes for bad experience
Clicking a cluster now only updates the right hand list view

improvement(map-ux): don't zoom on clusters, update right hand list

---

Procfile
api/package.json

We want to only build the app once when we merge to `master`. From there on we will promote the app through the pipeline. In order for this to work, we need to use the `release` even to trigger migrations as code moves through the pipe.
Removed migration execution from `heroku-postbuild` in `api/package.json` and moved it to `release` in the root level `Procfile`
closes #125

Use Heroku Release event to run post install actions

---

site/src/components/Section.js
site/src/sections/Resources.js
site/src/sections/Team.js

Description
-----------
Center the text inside sections.
Motivation
----------
In the current deployed site not all text is centered and can feel a bit strange to read the site.
Live preview: https://deploy-preview-191--reach4help.netlify.com/

Center text inside sections

---

.github/PULL_REQUEST_TEMPLATE.md
docs/TEAMS.md

Description
-----------
Rename "Application Security" team to "Security".
Once this is merged, I'll make the change effective in the GitHub org.
Motivation
----------
The tasks handled by people in the team also include things like network security and compliance, it makes more sense to rename it that way imo. Also for consistency, as the slack team and channel have that same name and it triggers me 😂.

Rename "application security" team to "security"

---

web-client/src/components/VerificationCode/VerificationCode.tsx

Description
-----------
Disable eslint rule anchor-is-valid for verification code page.
Motivation
----------
Verification code page  has an placeholder link and eslint is giving linting errors because of that.

Disable eslint anchor-is-valid for verification code page

---

.github/PULL_REQUEST_TEMPLATE.md

Description
-----------
Add a new line to the PR template to add a screenshot of the changes when the changes are visual.
Motivation
----------
When the changes are visual it's easier for the reviewers to also see a screenshot of the changes

docs(pr): add line to add screenshot if the pr changes visual

---

functions/src/models/users/index.ts

Description
-----------
Added a user setting to store the desired application that should load when users access the web client 
Motivation
----------
Users should be able to decide if they are a pin or a cav and switch between the two.

feat(models): add a default application preference field

---

web-client/src/components/CenteredCard/CenteredCard.tsx
web-client/src/components/GradientBackground/GradientBackground.tsx
web-client/src/index.css

fix for removing scrolling from cards, while remaining with card centred both on mobile and desktop. Leave commented CSS in case we want to make the cards transparent in the future for mobile layout.
Closes: #371

fix for removing scrolling from cards, while remaining with card centred

---

.gitignore
functions/src/models/requests/timeline.ts

Description
-----------
The timeline object can be used to track the request as well as the active offer (in case an offer is accepted or rejected along with the status change).
Motivation
----------
@puzzledbytheweb pointed out that UI can't render a timeline view if we don't track status changes of the request with a timestamp.

Adding timeline item

---

functions/src/questionnaires/functions.ts
functions/src/questionnaires/index.ts
functions/src/users/functions.ts
functions/src/users/index.ts

When a user completes a questionnaire (whatever that may be) they are automatically granted the correct PIN or CAV access based on the questionnaire.

When a user is created add the JWT claim for `pin: true`

---

firebase/firestore.rules

Ahead of #406
Allows anyone to write to create new markers (not edit existing ones), that save directly to the firestore database.
To be able to accept user data using the new form, allowing users to write directly to the firestore when creating new markers seemed like the best response.
This data isn't currently being used / loaded in the frontend. After this gets in and the initial form gets deployed, I'm going to add a new boolean property called `visible` that (can't be true when users submit) that will be indexed on, to allow users to query for the visible markers only. Marker submissions will then (for now) require a review by someone with appropriate access (currently only admins).
Beyond this I plan on allowing users to optionally view "hidden" fields before adding new information …

feat(backend): allow anyone to add markers to datastore

---

map/.eslintrc.js
map/src/App.tsx
map/src/components/add-information.tsx
map/src/components/footer.tsx
map/src/components/header.tsx
map/src/components/map.tsx
map/src/components/results.tsx
map/src/data/firebase.ts
map/src/data/markers.ts
map/src/i18n/index.tsx
map/src/i18n/langs/en.json
map/src/util/index.ts

This PR modifies the map to load the latest set of markers from the firebase database when the page loads. It also allows users to toggle whether or not "hidden" information is shown using a discreet button in the footer. The rationale behind this is that, for those submitting new information, we want them to be able to see whether anything else has been submitted / proposed in that same area before doing so themselves.
Right now the old data is still hard-coded, but we should migrate it over some time soon.
TODO (in later PRs probably):
* Make it obvious when a marker is "hidden" (e.g. less opacity? Note on the info page?)
* Automatically refresh results when users change filter / toggle visibility and their map position is unchanged.
* store a users preference to show hidden markers in …

feat(map): display firebase markers on map

---

package.json

We already had the `reach4help` GCP project, it just wasn't set up as a firebase project. I have done this now, and we should phase-out / delete the other production project.
This will lead to nicer URLs etc in our environment variables / project configurations etc...

chore(backend): update scripts to use reach4help as prod env

---

map/public/index.html
map/src/components/about.tsx
map/src/components/add-information.tsx
map/src/components/header.tsx
map/src/components/languages.tsx
map/src/util/tracking.ts

I've now deployed an instance of matomo to matomo.reach4help.org
with a letsencrypt TLS certificate (using bitnami). I've disabled
cookies completely in the tracking code, and it seems to work well
this should give us more than enough statistics for our site, and
we don't need to ask consent to drop cookies either!
Closes #290 
Closes #291

feat(map): enable anonymous (cookie-less) analytics using matomo

---

.firebaserc
.github/workflows/ci.yml
api/public/index.html
firebase.json
functions/package.json
functions/src/app.ts
functions/src/dispatch/fcm.ts
functions/src/https/api/index.ts
functions/src/https/api/map/index.ts
functions/src/https/index.ts
functions/src/index.ts
functions/src/models/markers/index.ts
functions/src/questionnaires/functions.ts
functions/src/questionnaires/index.ts
functions/src/requests/functions.ts
functions/src/users/functions.ts
functions/tests/triggers/user-triggers.test.ts

This is based on #501 (so should get merged after)
Introduces a new firebase "host" at api.reach4help.org (see: https://api.reach4help.org/edge/map/data) for creating general API endpoints for interacting with other projects.
As part of our collaboration with mutualaid.wiki, they need an endpoint to be able to consume our data. Once the mutual aid data has been migrated over to mutualaid.wiki, and we instruct users to enter new group information there instead of using our form, then it's unlikely there will be a continued need for mutualaid.wiki to ue this API, but it will remain useful for others!
(Note: we still need to transfer the hard-coded data to our database, hence the low result count)
cc @reach4help/security 
Closes #487
The majority of our …

Backend: introduce a REST API that allows people to consume our map data

---

functions/src/models/offers/index.ts
web-client/src/models/offers/index.ts

Added an additional value to the OfferStatus enum so that CAVs can decline requests by submitting an offer with status: `cav_declined`
CAV's need a way to only see requests that they haven't interacted with.
This is done by querying requests within a window and then also querying offers with the same conditions. Client side, users will join those collections.

feat(request): allow cavs the ability to decline requests

---

functions/src/models/users/index.ts
functions/src/models/users/privilegedInformation.ts
web-client/src/models/users/index.ts
web-client/src/models/users/privilegedInformation.ts
web-client/src/modules/requests/containers/CompletedRequestsContainer/CompletedRequestsContainer.tsx
web-client/src/modules/requests/containers/OngoingRequestsContainer/OngoingRequestsContainer.tsx
web-client/src/modules/requests/containers/OpenRequestsContainer/OpenRequestsContainer.tsx
web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx

This PR removes undefined attributes from the object to be sent to firestore without serializing and deserializing the object by using a reducer function.
This PR also removes the default assignment of the `applicationPreference` so that users are allowed to reach the `roleInfo` page and choose for themselves 
Firestore doesn't allow the value of an attribute to be `undefined`, the previous solution to fixing this error was to serialize the object into a string and then deserialize it into an object, thus removing all the `undefined` attributes. 
But this removed the properties of the `GeoPoint` data type and so the coordinates were saved as a `map` rather than `GeoPoint` on firestore.
This PR replaces the earlier approach with a reduce function.

fixes issues converting address for firestore and making applicationPreference optional

---

functions/src/models/users/privilegedInformation.ts
web-client/src/ducks/profile/actions.ts
web-client/src/models/users/privilegedInformation.ts
web-client/src/modules/personalData/components/PersonalDataForm/PersonalDataForm.tsx
web-client/src/modules/personalData/containers/PersonalDataFormContainer/PersonalDataFormContainer.tsx
web-client/src/pages/MasterPage.tsx
web-client/src/translations/en.json

Moves the option for opting-in for notifications and emails into the personal data page and removed from the new requests modal.
Also updates the `privilegedInformation` model in the `functions` project to make this field an optional field.
Also syncs the `web-client` version of the model with that of the `functions` 

moved the opt-in for emails and notifications to the personal data and model updates

---

web-client/src/components/DashboardLayout/DashboardLayout.tsx
web-client/src/components/MenuDrawer/MenuDrawer.tsx
web-client/src/pages/MasterPage.tsx
web-client/src/translations/en.json

Added the ability for user to switch between CAV/PIN 
Allows user to switch preference
In the side menu, click on the Switch to CAV/PIN link and make sure that the user profile is updated correctly

feat(menudrawer): add ability to switch application preference

---

.github/workflows/labeler.yml

Fix the automatic PR labeler, which fails on PRs from forks because of actions/labeler#12.
Make workflows work even when PRs come from a fork.

fix(ci):  add PR labels periodically to avoid issues with forks

---

web-client/src/components/WebClientMap/WebClientMap.tsx

Controls were all on the right.
Now are on Top Left and Top Right.
I hope that putting things on TOP will make them more accessible to small screens
The zoom control was hidden in this example using debugger tools.  Not sure if this is how an actual device would behave.  This change does not remedy the issue -- the zoom control is still hidden.  But the display is less crowded on other size displays.

distributing controls between right and left

---

site/src/components/header/index.js

When clicking on the links this happens:
I changed it to stop doing that

fix(dropdown): fix issue when clicking header links

---

web-client/src/components/BottomNavbar/BottomNavbar.tsx
web-client/src/components/Buttons/index.tsx
web-client/src/components/DashboardLayout/DashboardLayout.tsx
web-client/src/components/IntroLogo/IntroLogo.tsx
web-client/src/components/IntroWrapper/IntroWrapper.tsx
web-client/src/components/LoadingWrapper/LoadingWrapper.tsx
web-client/src/components/NotificationsDrawer/Notification.tsx
web-client/src/components/NotificationsDrawer/NotificationsHeader.tsx
web-client/src/components/NotificationsDrawer/NotificationsList.tsx
web-client/src/components/SideDrawerMenu/SideDrawerMenu.tsx

Code Conventions
All Component Names follow standard OO Naming conventions
* Inheritance Relationships can be indicated by appending the name of the subclass
* All styled-components must have meaningful names that indicate their usage within the markup.  
* They must be treated exactly the same as React Components
* The root styled-component for the module is {ModuleName}Container
* https://blog.elpassion.com/naming-101-quick-guide-on-how-to-name-things-a9bcbfd02f02
All css must occur in styled-components
Styled-components must be defined
* Use Props: defined at the bottom of the React component, after the return statement but before the terminal curly brace
* Do not use Props:  After the curly brace
----------------------------------------------
const BlogPost = ({props}) => (
< …

Styled Components renamed.  Css placed within them

---

web-client/src/components/figma/BlockStyles.ts
web-client/src/components/figma/TextStyles.ts
web-client/src/components/figma/index.ts

@sabind @ashwinkjoseph 
This work is preliminary.
Do you think this is a good way to proceed?
I don't know whether predefined BlockStyles will be that useful.
Also, Headers are block-level rather than inline styles, so I am using "H1Text" instead of "H1" as names.
The idea is to start making people do:
< BlockStyle >
< TextStyle >
content
< / TextStyle >
< / BlockStyle >

base text styles from figma

---

web-client/src/modules/requests/components/NewRequest/NewRequest.tsx

The field should always be `required:true` because `mayBeOtherField()` only renders the field when it is needed.
solves #852

fix: make 'please enter your type' textbox mandatory #852

---

web-client/src/components/Buttons/index.tsx
web-client/src/modules/requests/components/RequestItem/RequestItem.tsx

Made styling adjustments to the "Cannot Help" button so the text doesn't go out of the button's boundaries.
To polish the aesthetic of the request item. To improve user's readability.

fix: adjusted cannot help button
