reach4help/reach4help

- site/src/components/Footer.js
> fix(footer): fix social icons position footer

- map/package.json
- map/src/App.tsx
- map/src/components/filters.tsx
- map/src/components/header.tsx
- map/src/components/map-loader.tsx
- map/src/components/map.tsx
- map/src/components/results.tsx
- map/src/components/search.tsx
- map/src/data/index.ts
- map/src/data/markers.ts
- map/src/index.tsx
- map/src/styling/index.ts
- map/src/styling/theme.ts
Added alabama, arizona and california datapoints from here: https://docs.google.com/document/d/1uP49OQGhosfBN4BOYQvyy_Mu3mpCSOYzip13LksC-S8/edit#
Also:
* Changed the data model for markers quite a bit to fit the data I was stuffing in, and make it more flexible
* Added some initial intro paragraphs
* Styled search bar to overlay map and look like other map UI elements
* Update the URL whenever we zoom or PAN, and restore the position form the URL on load / reload (will also enable sharing a specific location)
Ideas I've had, but not for this PR:
* Clicking on markers should zoom to level depending on service radius
* should be able to select a marker from list even when clustered (many markers will share exact same location)
* detailed information should display in sidebar (rather than …
> Some initial styling, and additional markers

- web-client/package.json
- web-client/src/components/Button/Buttons.ts
- web-client/src/containers/exampleContainer.tsx
This PR setups styled-components.
Closes #56
> [RFC8[#56] setup styled components

- map/src/components/map.tsx
- map/src/data/markers.ts
Also caught a bug where links opened in the same window.
> Adding data for WI, WY, and WA USA

- map/src/components/header.tsx
- map/src/components/map.tsx
- map/src/components/results.tsx
- map/src/components/search.tsx
- map/src/data/markers.ts
Fixed crash with "replaceHistory"
> Adding more data (VT) and fixing bugs

- web-client/src/store/index.ts
> [RFC][#143] Fix no redux devtools crash 

- SECURITY.md
This is a first version of the security policy, the supported version will be updated once we release a first version.
> docs: first security policy version

- map/package.json
- web-client/package.json
- yarn.lock
> fix: update react-scripts in map and web-client to fix build

- .github/workflows/build-deploy-map.yml
- map/package.json
- map/public/CNAME
Successful deploy here: https://github.com/reach4help/reach4help/runs/533730215?check_suite_focus=true
> ci(map): deploy map automatically when master is updated

- web-client/.dockerignore
- web-client/Dockerfile
- web-client/README.md
- web-client/docker-compose.yml
- web-client/package.json
- web-client/src/components/Button/Buttons.ts
- web-client/src/containers/exampleContainer.tsx
- docker
- docker-compose
Command to run the frontend with docker `docker-compose up -d`
closes #168
> [RFC][#168] Add docker virtualisation to frontend

- .gitignore
- api/src/database/database.providers.ts
- api/src/database/ormconfig.ts
- api/src/users/dto/create-user.dto.ts
- api/src/users/users.service.ts
Description
-----------
Fix several issues (not actual GH issues):
- DTO compilation broke build
- Migrations weren't actually running
Motivation
----------
Heroku build is broken currently and this will fix it.
None, CI/CD will test this as part of the deploy
If you checked any of those, please request a review from `@application-security`.
None
> fix(api): fix a breaking changed merged by ERD PR

- map/src/App.tsx
- map/src/components/footer.tsx
re #176
Description
-----------
Motivation
----------
If you checked any of those, please request a review from `@application-security`.
If this PR fixes an issue, please add "closes #issue-id" here, otherwise add a reference to the issue it relates to.
> feat(footer): add references needed before migration to Netlify

- map/yarn.lock
- site/yarn.lock
Description
-----------
Motivation
----------
If you checked any of those, please request a review from `@application-security`.
If this PR fixes an issue, please add "closes #issue-id" here, otherwise add a reference to the issue it relates to.
> Convince Netlify to use yarn

- site/src/components/Header.js
- site/src/sections/Landing.js
Description
-----------
Add button to map project on reach4help.org
Motivation
----------
If you checked any of those, please request a review from `@application-security`.
closes #169
> feat(site): add link to map on landing page

- .github/PULL_REQUEST_TEMPLATE.md
Description
-----------
Make instructional comments html comments so they are hidden, and change the mention of application-security to the full handle that should be used.
Motivation
----------
looks cleaner :)
> docs: improve pr template

- map/src/App.tsx
- map/src/components/header.tsx
- map/src/styling/index.ts
Description
-----------
Motivation
----------
Doesn't yet work well responsively / on small devices. Displaying this message for the time being.
> feat(map): display message for small devices

- site/static/.well_known/security.txt
Description
-----------
Add a security.txt file to the .well-known directory, as per [security.txt](https://securitytxt.org/).
Motivation
----------
Allow security researchers to properly report findings related to this project.
closes #50
> feat(site): add a security.txt well-known file

- map/src/data/markers.ts
- yarn.lock
Description
-----------
test/partial data entry
Motivation
----------
add to the map data, and check with project maintainers re formatting before trying to add dozens/hundreds with e.g. a script
- [ x ] I have a plan for how to revert, rollback, or disable these changes if things are not working as expected
- [ x ] User data: personal information handling, logs, error messages, etc.
closes #209
> chore: add dc blm data

- package.json
Description
-----------
Fix build problem in #228 
reference: https://github.com/vuejs/vue-cli/issues/5043#issuecomment-571463204
I don't know why this solves 🤔 
Motivation
----------
> chore(workspace): add mini-css-extract-plugin

- web-client/.eslintignore
- web-client/package.json
- web-client/src/pages/MasterPage.tsx
- web-client/src/pages/ProtectedPage.tsx
- web-client/src/pages/routes/LoginRoute/constants.tsx
- web-client/src/types/miragejs.d.ts
- web-client/src/types/react-app-location.d.ts
- web-client/src/types/react-facebook-auth.d.ts
- yarn.lock
Description
-----------
Adds react-app-location to solve routing
Motivation
----------
Routing can be tricky. This gives a bit consistency to it. 
> feat(routes): add react-app-location

- web-client/package.json
- web-client/src/components/FacebookLoginButton/FacebookLoginButton.tsx
- web-client/src/containers/LoginContainer/LoginContainer.tsx
- web-client/src/ducks/auth/actions.ts
- web-client/src/ducks/auth/reducer.ts
- web-client/src/ducks/auth/types.ts
- web-client/src/firebase/index.ts
- web-client/src/http/resources/auth.ts
- web-client/src/store/middlewares/injectRequestMiddleware.ts
Description
-----------
This PR adds firebase as a dependency in the web-client project.
The Configuration file for configuring firebase as per the environment has been created, this file will export an initialized firebase App instance, firebase auth instance and a firestore instance
The Configuration file can choose firebase configuration depending on the NODE_ENV, however I have manually put it to development for the time being
To Demonstrate how to use firebase with redux, I have implemented Facebook Sing in with Firebase Authentication and have changed the onclick callback of the singin in button to call the action creator for firebase auth
Motivation
----------
https://github.com/reach4help/reach4help/issues/231
https://github.com/reach4help/reach4help/issues/231 …
> Firebase Integration and Facebook Sign In with Firebase

- map/src/App.tsx
- map/src/components/header.tsx
- map/src/components/map-utils/google-maps.ts
- map/src/components/map.tsx
- map/src/components/results.tsx
- map/src/styling/index.ts
- map/src/styling/mixins.ts
Description
-----------
Leaving this PR open while I work on the responsive design for the map, to get deployments on netlify to test on my phone :)
Don't merge yet! But ideas and feedback welcome in this PR.
TODO:
Motivation
----------
Try it on mobile and tablets etc...
Related to #75
> Improve responsiveness of map

- functions/package.json
- map/package.json
- package.json
- web-client/package.json
Description
-----------
- removed `--fix` on `pre-commit`
- make sure all projects in monorepo have `lint:fix` command
- added top level `yarn run lint:fix` command
Motivation
----------
auto lint fixes have caused *production* outages.
> ci: remove lint fix as pre-commit hook

- site/src/content/thanks.md
- site/src/pages/index.js
- site/src/sections/Thanks.js
Description
-----------
Add a section to highlight who has helped us get here
Motivation
----------
Give back to the orgs and brands that help us
> feat(thanks): add a thank you section

- CONTRIBUTING.md
- docs/GETTING_INVOLVED.md
- docs/MVP.md
- docs/TEAMS.md
Description
-----------
Clean up Onboarding Documentation, ala #254
> docs: update onboarding documentation

- docs/TEAMS.md
Add Dan for User Testing team
(I was working off an old branch of info repo in #256)
> docs: add missing user-testing team changes

- README.md
Description
-----------
Just updating the readme for new volunteers and visitors to better understand our mission and project.
Motivation
----------
> Updating readme for onboarding rework

- site/gatsby-config.js
- site/src/components/SocialLink.js
- site/src/content/resources.md
- site/src/content/team.md
- site/src/sections/Landing.js
Description
-----------
Ala #254
- Add a "Get Involved" button on the landing page
- Update old refs to info repo
- Link to our linkedin page
> Update site following getting involved onboarding doc updates

- docs/TEAMS.md
Description
-----------
Add @TheRealAlexV to the security team.
Motivation
----------
> add AlexV to the security team

- web-client/src/components/VerificationCode/VerificationCode.tsx
- web-client/src/pages/routes/VerificationCodePage.tsx
- web-client/src/translations/translations.json
Description
-----------
Add page to verify code sent to user phone number
Motivation
----------
Issue #99
> feat(page): add verify phone number page

- README.md
- functions/README.md
Description
-----------
Provide information for the backend.
Motivation
----------
We don't have a README.
> Create Back End README

- map/src/components/map-utils/google-maps.ts
Description
-----------
Changed the default coordinates in the options parameter. Used the average of both latitude and longitude values.
Motivation
----------
Visual changes are already presented in issue #287 
closes #287
> feat(map): change default options in map creation

- site/src/content/thanks.md
Description
-----------
Add Datadog to the site's thank you section.
Motivation
----------
Datadog supports us as our monitoring solution.
> feat(site): add datadog to thank you section

- .all-contributorsrc
Description
-----------
Motivation
----------
> fix: fix error on all-contributorsrc

- map/src/data/markers.ts
Adding map markers for San Diego, CA
Contributing to map comprehensiveness
Check that new markers populate in the map / side panel
> add San Diego markers

- map/src/components/map.tsx
updateMarkersVisiblilityUsingFilter --> updateMarkersVisibilityUsingFilter
https://github.com/reach4help/reach4help/issues/349
> Fixed typo

- site/src/content/thanks.md
https://github.com/reach4help/reach4help/issues/261
> Added Slack to the list of thank you's on site

- map/src/App.tsx
- map/src/components/map.tsx
Added another button to the bottom of map. Created a wrapper for styling the group of buttons. Implemented handler function.
Here're the visual changes:
closes #289
> feat(map): add center to my location button

- map/src/data/markers.ts
Added some organizations to Portugal, since we are lacking there.
We'll be rolling out to Portugal but if one sees the map it looks like we are not active there
> chore(map): add orgs from Portugal

- web-client/src/components/GradientBackground/GradientBackground.tsx
Changed background gradient.
Visual changes presented in #201
closes #201
> improvement(frontend): change background gradient

- .github/zenhub-issue-sync/dist/index.js
- .github/zenhub-issue-sync/src/index.ts
* Include which epics an issue is part of
* Remove some spurious curly braces
> Improvements to ZenHub issue sync

- docs/GETTING_INVOLVED.md
Addressing #387, replacing expired Slack invite link with one that never expires.
> Fixing expired Slack invite link

- .github/CODEOWNERS
- .github/labeler.yml
- .github/workflows/labeler.yml
This PR implements 2 things:
- adds the "labeler" action, to automatically label PRs depending on the modified files
- adds a code owner file, to automatically request a review from teams in charge of the code being modified
Once this PR is merged, I will enforce code owner review requirement in the repository settings.
A lot of PRs are created/merged without any label being added, which makes reviewing code more painful. This should hopefully make the process easier.
> Automated PR triage

- .idea/covidaid.iml
- functions/src/offers/index.ts
- functions/src/requests/index.ts
- functions/src/users/index.ts
- functions/tests/firestore-rules.test.ts
- functions/tests/index.test.ts
- functions/tests/triggers/user-triggers.test.ts
Update some of the trigger functions
Reviewing the code @ashwinkjoseph wrote + adding some changes.
> fix: updated some of the code

- README.md
Fixed little typo reguarly -> regularly 
> fix(docs): fix typo in `who we are` section

- map/src/components/header.tsx
> Fix typo on map header

- functions/package.json
- functions/src/algolia/index.ts
- functions/src/requests/index.ts
- functions/yarn.lock
@telmodias this one is for you. All requests added to the db will be indexed in https://algolia.com. I've applied for our free COVID-19 pricing.
Allow text searching of request objects.
> feat(text-search): algolia-request-text-search

- .github/zenhub-issue-sync/dist/index.js
- .github/zenhub-issue-sync/src/index.ts
The sync is broken when PRs have dependency links or epics as they were filtered out. This updates the script to only filter them out from the issues that have descriptions updated.
> ci(zenhub): fix zenhub sync to allow linking to PRs / PRs to have epics

- map/src/i18n/langs/af.json
- map/src/i18n/langs/ar.json
- map/src/i18n/langs/ca.json
- map/src/i18n/langs/cs.json
- map/src/i18n/langs/da.json
- map/src/i18n/langs/de.json
- map/src/i18n/langs/el.json
- map/src/i18n/langs/es.json
- map/src/i18n/langs/fi.json
- map/src/i18n/langs/fr.json
- map/src/i18n/langs/he.json
- map/src/i18n/langs/hu.json
- map/src/i18n/langs/it.json
- map/src/i18n/langs/ja.json
- map/src/i18n/langs/ko.json
- map/src/i18n/langs/nl.json
- map/src/i18n/langs/no.json
- map/src/i18n/langs/pl.json
- map/src/i18n/langs/pt.json
- map/src/i18n/langs/ro.json
- map/src/i18n/langs/ru.json
- map/src/i18n/langs/sr.json
- map/src/i18n/langs/sv.json
- map/src/i18n/langs/tr.json
- map/src/i18n/langs/uk.json
- map/src/i18n/langs/vi.json
- map/src/i18n/langs/zh.json
These conflicts were introduced by ru.json being changed in `master` and `i18n-master` simultaneously.
> Resolve conflicts with i18n from crowdin

- map/src/data/markers.ts
Added Carbondale Colorado U.S.A. mutual aid group.
> Added Carbondale Colorado U.S.A. mutual aid group

- map/src/components/filters.tsx
- map/src/components/languages.tsx
- map/src/components/results.tsx
- map/src/i18n/index.tsx
- map/src/i18n/langs/ar.ts
- map/src/i18n/langs/fr.ts
- map/src/i18n/langs/pt.ts
- map/src/styling/mixins.ts
We have enough strings translated for these languages, so we can enable them now! :)
> feat(map): Enable arabic, french and portuguese

- functions/src/models/users/privilegedInformation.ts
- functions/src/users/privilegedFunctions.ts
- functions/src/users/privilegedInformation.ts
This PR adds an additional data field to the Privileged Information Sub Collection of a User Document that stores the "raw" address entered by the user apart from the one obtained from Google Geocode API.
This PR also completes the onCreate trigger for the privileged information sub-collection.
Users should be able to see the exact data that is being entered by them.
We should use Geocode API to retrieve the Latitude and Longitude of the address entered by the user.
The current Interface suggested storing the result of the Geocode operation directly in the document as the address.
The problem with this is that the address fields returned by Google may not be the exact ones that the user has agreed as correct by typing it, even if it is close to the one that the user entered or more …
> Additional Field in Privileged User Info

- web-client/src/constants/mediaQueries.ts
- web-client/src/modules/request/components/NewRequestForm/NewRequestForm.tsx
- web-client/src/modules/request/index.ts
- web-client/src/types/constants.d.ts
Now that we have the design for the mobile version I've completed that in the New Request page.
To win small victories and complete this a bit further :)
Relates to: https://github.com/reach4help/reach4help/issues/162
> [MVP] - New Request Page mobile styling

- map/src/i18n/index.tsx
- map/src/i18n/langs/es.ts
- map/src/i18n/langs/hi.ts
- map/src/i18n/langs/tr.ts
- map/src/i18n/langs/zh.ts
> feat(map): enable 4 more languages

- web-client/src/translations/translations.json
> fix: bellow -> below

- site/src/content/thanks.md
Adding more links to the companies that support our efforts.
Giving thanks 👍 
> fix: more thanks

- web-client/src/ducks/auth/reducer.ts
- web-client/src/ducks/profile/actions.ts
- web-client/src/ducks/profile/functions.ts
- web-client/src/ducks/profile/reducer.ts
- web-client/src/ducks/profile/types.ts
- web-client/src/modules/personalData/components/PersonalDataForm/PersonalDataForm.tsx
- web-client/src/modules/personalData/components/RoleInfo/RoleInfo.tsx
- web-client/src/modules/personalData/containers/PersonalDataFormContainer/PersonalDataFormContainer.tsx
- web-client/src/modules/personalData/containers/RoleInfoContainer/RoleInfoContainer.tsx
- web-client/src/modules/personalData/pages/ContentPage.tsx
- web-client/src/modules/phone/components/PhoneNumberEntryForm/PhoneNumberEntryForm.tsx
- web-client/src/modules/phone/components/PhoneNumberVerifyForm/PhoneNumberVerifyForm.tsx
- web-client/src/pages/routes/ProtectedRoute.tsx
- web-client/src/store/middlewares/observerMiddleware.ts
This PR will complete the integration of Personal Data Page Module by fetching and auto-filling personal data from firestore and also doing proper redirections and routing in both Protected Route Component as well as the ContentPage within the Module.
This PR also completes the Integration of the RoleInfo Page which lets users choose their Application Preference. (The UI is still not ready for mobile, someone has to do that)
> Completes Personal Data Page and Role Info Page Integration and Redirections

- functions/package.json
- functions/src/requests/functions.ts
- functions/src/users/functions.ts
- functions/tests/triggers/requests-triggers.test.ts
- functions/tests/triggers/user-triggers.test.ts
This PR is an attempt at establishing a procedure for writing tests for firestore Triggers.
This uses the @firebase/testing library for when the functions are run in test env while uses the real SDKs once the app database URL is available.
This uses offline method, while not having to mock every method by using the `@firebase/testing` SDK but for triggers, using the wrapping method provided by `firebase-functions-test` package for forcing the execution of the trigger.
This, therefore, combines the benefits of the Emulator with the Tools provided for Online method of testing.
We needed a method to test the Triggers in a fast, dependable and predictable manner while also not having to use a separate Firebase Project Just for testing and avoid the hassle of managing the secrets of the test …
> Tests for Triggers

- map/src/App.tsx
- map/src/components/filter-visibility.tsx
- map/src/components/map-layout.tsx
- map/src/components/map-utils/map-state.ts
- map/src/components/map.tsx
- map/src/data/index.ts
- map/src/i18n/langs/en.json
- map/src/state/index.ts
A drop-down will be made visible when users have enabled hidden markers to allow users to filter which markers are displayed on the  map (most useful for displaying only hidden markers to check review).
closes #476
> feat(map): allow users to filter by marker visibility

- map/src/data/firebase.ts
> feat(map): store user preference for displaying hidden results

- functions/src/https/api/map/index.ts
- model/src/markers/index.ts
Following the data migration, this data should now be made available.
See:
* https://api.dev.reach4help.org/edge/map/data
* https://api.reach4help.org/edge/map/data
> Map: include hardcoded data in the API

- firebase/storage.rules
- functions/package.json
- functions/src/app.ts
- functions/src/https/api/map/index.ts
- functions/src/index.ts
- functions/src/models/markers/index.ts
- functions/src/pubsub/index.ts
- functions/src/pubsub/schedule/generate-data-files.ts
- functions/src/pubsub/schedule/index.ts
- functions/src/pubsub/schedule/sync-mutualaid.wiki.ts
- functions/yarn.lock
- map/src/App.tsx
- map/src/components/about.tsx
- map/src/components/add-information.tsx
- map/src/components/footer.tsx
- map/src/components/map.tsx
- map/src/components/results.tsx
- map/src/data/firebase.ts
- map/src/i18n/langs/en.json
- model/src/markers/index.ts
This is quite a heafty PR. The overall effect of which is to include the 3000+ groups from https://mutualaid.wiki in our map's data-set, and update the UI with attribution, and direct people to add mutual aid groups on that site instead of ours from the Add information window.
A few changes needed to be made to accommodate the vast increase in datapoints on the map. The main changes in this PR are:
* Introduction of a new cloud function to sync with mutualaid.wiki (needs to be converted to cron)
* Introduction of a new cloud function to cache the contents of the markers collection as a JSON file (in firebase storage) that can be downloaded by clients instead of directly reading the 3000+ entries from firebase (which is a lot slower, and eats into our usage)
* Updating the Map to download …
> Map: incorporate mutualaid.wiki data in our map

- map/src/components/map.tsx
> fix(map): clear slected result when clicking on a cluster

- map/src/components/map-utils/google-maps.ts
- map/src/components/map-utils/map-state.ts
- map/src/components/map.tsx
- map/src/components/my-location-button.tsx
This should be decent enough for our enabling the additional markers for now
> Map: performance improvements

- web-client/README.md
- web-client/package.json
- web-client/src/modules/personalData/components/PersonalDataForm/PersonalDataForm.tsx
- yarn.lock
The Dockerfile and the docker-compose configuration itself hasn't been changed, but the fixes were made to the codebase such as explicitly adding the package `@types/googlemaps` and fixing an issue with the use of a `Button` component which wasn't causing issues when run with `yarn` directly but was causing issues when running as a docker container
A few of the newly onboarded developers were reporting issues with getting the project to run with docker. 
This will reduce the friction for new members to get the project up and running and start developing without too much of a hassle
> fixed erros when ran with docker and added documentation

- web-client/src/ducks/requests/actions.ts
- web-client/src/ducks/requests/functions.ts
- web-client/src/ducks/requests/reducer.ts
- web-client/src/ducks/requests/types.ts
- web-client/src/modules/index.ts
- web-client/src/modules/requests/components/RequestList/RequestList.tsx
- web-client/src/modules/requests/containers/CompletedRequestsContainer/CompletedRequestsContainer.tsx
- web-client/src/modules/requests/containers/OngoingRequestsContainer/OngoingRequestsContainer.tsx
- web-client/src/modules/requests/containers/OpenRequestsContainer/OpenRequestsContainer.tsx
- web-client/src/modules/requests/index.ts
- web-client/src/modules/requests/pages/ContentPage.tsx
- web-client/src/modules/requests/pages/routes/CompletedRequestsRoute/CompletedRequestsRoute.tsx
- web-client/src/modules/requests/pages/routes/CompletedRequestsRoute/constants.tsx
- web-client/src/modules/requests/pages/routes/OngoingRequestsRoute/OngoingRequestsRoute.tsx
- web-client/src/modules/requests/pages/routes/OngoingRequestsRoute/constants.tsx
- web-client/src/modules/requests/pages/routes/OpenRequestsRoute/OpenRequestsRoute.tsx
- web-client/src/modules/requests/pages/routes/OpenRequestsRoute/constants.tsx
- web-client/src/pages/MasterPage.tsx
The Request Module was created in the project
> Request Module

- site/gatsby-config.js
> Fixed Instagram Change

- functions/src/https/api/map/index.ts
- functions/src/models/markers/index.ts
- functions/src/pubsub/schedule/index.ts
- functions/src/pubsub/schedule/sync-mutualaid.wiki.ts
- functions/src/pubsub/schedule/sync-mutualaidhub.ts
- functions/src/pubsub/schedule/sync-util.ts
- map/src/components/about.tsx
- map/src/components/results.tsx
- map/src/i18n/langs/en.json
- model/src/markers/index.ts
Regularly sync & import data from mutualaidhub.org, include attribution in the UI, and include this data (and public domain license) in our API.
> Map: include data from mutualaidhub.org

- functions/src/models/users/privilegedInformation.ts
- web-client/src/models/users/privilegedInformation.ts
> Align Models - Capture if we can send info

- .all-contributorsrc
Adds @mcverter and me to all-contributors. If anyone checks this PR and wants to be added feel free to comment/adding a commit to this.
Giving credit and making visible to others that might want to be in our front page
> chore(all-contributors): add mcverter and puzzledbytheweb

- web-client/src/components/WebClientMap/WebClientMap.tsx
current GetMyLocation UI also needs to PAN to the location after loading it.
> fixing getMyLocation.  pans to current center

- .all-contributorsrc
- web-client/src/modules/personalData/components/PersonalDataForm/PersonalDataForm.tsx
- web-client/src/modules/phone/components/PhoneNumberEntryForm/PhoneNumberEntryForm.tsx
- web-client/src/modules/phone/components/PhoneNumberVerifyForm/PhoneNumberVerifyForm.tsx
- web-client/src/modules/phone/containers/PhoneEntryContainer/PhoneEntryContainer.tsx
- web-client/src/theme/colors.js
- web-client/src/translations/en.json
Fixed a couple of validations on phone entry and verify form. Updated checkbox alignment on mobile view on the personal data form + some minor fixes.
#604 
#590 
#603 
#600 
#577 
'Verify' capitalization issue 
Alignment and Spacing fix:
"Blurry" T&C line text:
Error handling:
> fix: phone entry/verify validations and other minor fixes

- web-client/src/components/WebClientMap/utils.tsx
Radial Distance function (Haversine Distance)
> Radial Distance function (Haversine Distance)

- web-client/src/modules/login/pages/ContentPage.tsx
- web-client/src/modules/personalData/pages/ContentPage.tsx
- web-client/src/modules/phone/pages/ContentPage.tsx
- web-client/src/modules/requests/pages/ContentPage.tsx
- web-client/src/modules/timeline/pages/ContentPage.tsx
Code splitting with lazy load and suspense
Improve application performance by splitting the bundle into smaller chunks
Some performance metrics:
Note: this was taken on incognito mode without any extensions being enabled
**Before:**
Login - 
Inside App -
**After:** 
Login - 
Inside App -
> Lazy load components

- map/package.json
- site/package.json
- web-client/package.json
- yarn.lock
> Site redesign

- web-client/package.json
- web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx
- web-client/src/pages/MasterPage.tsx
- web-client/src/translations/en.json
https://github.com/reach4help/reach4help/issues/617
More Descriptive Page Titles
> adding page subtitles

- web-client/src/modules/requests/components/NewRequest/NewRequest.tsx
- yarn.lock
Removes Get Current Location from the new request form and instead just uses the new one in the map
> fix: styling issues with buttons in the new request page

- web-client/src/modules/requests/components/RequestList/RequestList.tsx
Replace Loading text with loading indicator on request list pages
https://github.com/reach4help/reach4help/issues/656
> Replace Loading text with loading indicator on request list pages [Bug#656]

- site/src/components/seo.js
> fix: seo for www site

- web-client/src/modules/requests/containers/AcceptedRequestsContainer/AcceptedRequestsContainer.tsx
- web-client/src/modules/requests/containers/OngoingRequestsContainer/OngoingRequestsContainer.tsx
- web-client/src/translations/en.json
> template string fixes

- web-client/src/components/BottomNavbar/BottomNavbar.tsx
- web-client/src/components/DashboardLayout/DashboardLayout.tsx
- web-client/src/components/NotificationsDrawer/NotificationsDrawer.tsx
- web-client/src/ducks/requests/functions.ts
This PR fixes issues with notifications not showing up properly and also highlighting the notifications bell icon in red when new notifications are present.
The PR also has a commit which increases the radius of the search for open requests from 5 miles to 500 Miles (a temporary global until algolia is implemented at which point, we can migrate the backend while allowing the interface to remain the same)
> Notifications

- web-client/package.json
- web-client/src/modules/timeline/components/TopPanel/TopPanel.tsx
- web-client/src/translations/i18n.ts
In Desktop, it hides the SMS and adds the phone number as text
> Showing the number as text when in desktop

- web-client/src/translations/en.json
Updated the "Login Screen" text prompt. I could use some help maybe adjusting the CSS to fit the text better on screen as well as condense the whole view to minimize scrolling.
@btuerker @mcverter If you have any suggestions let me know. 
Optimize the sign in flow so we don't have such steep drop-off. We should at least aim to tell users about our motivation and process.
> fix: updated sign-up text

- web-client/package.json
- web-client/src/modules/requests/containers/AcceptedRequestsContainer/AcceptedRequestsContainer.tsx
- web-client/src/modules/requests/containers/ArchivedRequestsContainer/ArchivedRequestsContainer.tsx
- web-client/src/modules/requests/containers/FindRequestsContainer/FindRequestsContainer.tsx
- web-client/src/modules/requests/containers/FinishedRequestsContainer/FinishedRequestsContainer.tsx
- web-client/src/modules/requests/containers/OngoingRequestsContainer/OngoingRequestsContainer.tsx
- web-client/src/modules/requests/containers/OpenRequestsContainer/OpenRequestsContainer.tsx
- web-client/src/modules/timeline/components/TopPanel/TopPanel.tsx
- web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx
- web-client/src/translations/i18n.ts
- yarn.lock
Fixes Internationalisation by using auto-detect using the browser's `navigator`
Fixes refresh states of all pages by clearing the states whenever a page is loaded
Fixes the page to which a user is taken when they click on an accepted request in the notifications
Old data still persisted in many pages after the user comes back to the page from another page, this was impacting the smoothness of the app.
The app wasn't changing languages based on the user's browser settings
> Fixes to the current Prod env

- site/src/components/header/index.js
- web-client/src/modules/timeline/components/TopPanel/TopPanel.tsx
> Conflicts between Master branch and Production

- web-client/src/firebase/index.ts
Code added to turn on firebase analytics.
Start tracking analytics
> firebase analytics

- web-client/src/firebase/index.ts
New changes were made to the `master` branch directly. These have to be synced to the `development` branch
> Syncing master to development

- functions/src/https/api/requests/index.ts
- web-client/src/ducks/offers/functions.ts
- web-client/src/ducks/offers/reducer.ts
- web-client/src/ducks/offers/types.ts
- web-client/src/ducks/requests/reducer.ts
- web-client/src/modules/requests/containers/FindRequestsContainer/FindRequestsContainer.tsx
- web-client/src/modules/timeline/components/BottomPanel/BottomPanel.tsx
- web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx
- web-client/src/translations/en.json
- yarn.lock
1. Fixes issue with CAV rejecting a request
2. the issue with timeline module when the PIN accepts the offer while the CAV has the request open on their phone
3. the issue with rating where a user is being asked to rate themselves
> Fixes to Production App

- web-client/src/firebase/index.ts
Adds the performance metrics SDK. Firebase detects the SDK but takes up to 24 hours to start populating the dashboard with data.
Add the correct `REACT_APP_FIREBASE_MEASUREMENT_ID` and check the dashboard in firebase
closes #792 since #797 is already merged
> feat(telemetry): add firebase performance SDK

- web-client/src/modules/personalData/components/PersonalDataForm/PersonalDataForm.tsx
- web-client/src/translations/en.json
- I added specific error messages for the city and country form fields.
- I added interpolation to terms & condition field to prevent possible translation issues.
- I also refactored the language file, but it will cause us to rewrite all the translations made before. If we don't want to deal with it right a moment, I'll remove those changes.
#663 
> Fix PersonalDataFrom fields error messages

- functions/src/https/api/requests/index.ts
- web-client/src/modules/requests/components/NewRequest/NewRequest.tsx
- web-client/src/modules/timeline/components/BottomPanel/BottomPanel.tsx
- web-client/src/modules/timeline/components/OffersList/OffersList.tsx
- web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx
Fixes:
Issue with requests being deleted when a PIN cancels/removes a request
Issue with Archived requests not working in timeline module
Issue with Removed requests not showing up for a CAV
Issue with CSS in offer list for Chrome/Webkit (a fix is still required for Mozilla)
Issue with Translation in Offer List page
Issue with Default value in new requests form
Noticed some major bugs which maybe considered as immediate or urgent bugs and since we were merging this into prod today, seemed like it's best to do this in staging than in prod.
> Staging Bug Fixes

- web-client/src/components/Buttons/index.tsx
- web-client/src/components/CenteredCard/CenteredCard.tsx
- web-client/src/components/figma/BlockStyles.tsx
- web-client/src/components/figma/index.ts
- web-client/src/modules/login/components/FacebookLoginButton/FacebookLoginButton.tsx
- web-client/src/modules/login/components/GoogleLoginButton/GoogleLoginButton.tsx
- web-client/src/modules/login/components/LoginFooter/LoginFooter.tsx
- web-client/src/modules/login/components/RegistrationSteps/RegistrationSteps.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step1SelectLanguage.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step2Authentication.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step3EmailSignIn.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step4EmailRegistration.tsx
- web-client/src/translations/en.json
Updated the styling (and some text) to be more aligned with @r13serra11's Figma designs. **No underlying logic was touched**, just a lot of CSS. Gets a bit cramped in smaller screens (4" iPhone 5) but it should work fine everywhere else. 
Part of #832
> Making sign up design more consistent with Figma

- web-client/src/components/Buttons/index.tsx
- web-client/src/components/CenteredCard/CenteredCard.tsx
- web-client/src/components/figma/BlockStyles.tsx
- web-client/src/components/figma/index.ts
- web-client/src/modules/login/components/FacebookLoginButton/FacebookLoginButton.tsx
- web-client/src/modules/login/components/GoogleLoginButton/GoogleLoginButton.tsx
- web-client/src/modules/login/components/LoginFooter/LoginFooter.tsx
- web-client/src/modules/login/components/RegistrationSteps/RegistrationSteps.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step1SelectLanguage.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step2Authentication.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step3EmailSignIn.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step4EmailRegistration.tsx
- web-client/src/translations/en.json
Reverts reach4help/reach4help#846
There are issues with CSS which cuts off the form in the personal data page
> Revert "Making sign up design more consistent with Figma"

- web-client/src/components/Buttons/index.tsx
- web-client/src/components/CenteredCard/CenteredCard.tsx
- web-client/src/components/figma/BlockStyles.tsx
- web-client/src/components/figma/index.ts
- web-client/src/modules/login/components/FacebookLoginButton/FacebookLoginButton.tsx
- web-client/src/modules/login/components/GoogleLoginButton/GoogleLoginButton.tsx
- web-client/src/modules/login/components/LoginFooter/LoginFooter.tsx
- web-client/src/modules/login/components/RegistrationSteps/RegistrationSteps.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step1SelectLanguage.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step2Authentication.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step3EmailSignIn.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step4EmailRegistration.tsx
- web-client/src/translations/en.json
Reverts reach4help/reach4help#846
turns out the problems introduced from this PR wasn't the major reason and is still acceptable.
> Revert "Revert "Making sign up design more consistent with Figma""

- web-client/src/components/CenteredCard/CenteredCard.tsx
- web-client/src/components/figma/BlockStyles.tsx
- web-client/src/index.css
- web-client/src/modules/login/components/LoginFooter/LoginFooter.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step3EmailSignIn.tsx
- web-client/src/modules/login/components/RegistrationSteps/Step4EmailRegistration.tsx
- web-client/src/modules/login/containers/LoginContainer/LoginContainer.tsx
@ashwinkjoseph mentioned there are some issues with smaller devices and scrolling, which this fixes. 
> Added better styling for smallER devices + scrolling (#846 p2)

- web-client/src/modules/timeline/components/OffersList/OffersList.tsx
fixes bug https://github.com/reach4help/reach4help/issues/858
If the status is "cav_declined" the offer will not show.
> refactoring to remove for loop.  adding rule for status validity

- web-client/src/modules/login/components/RegistrationSteps/Step1SelectLanguage.tsx
https://github.com/reach4help/reach4help/issues/856
> language dropdown in own language

- web-client/src/components/WebClientMap/WebClientMap.tsx
This fixes the issue, https://github.com/reach4help/reach4help/issues/862
However, adjusting the top css feels a bit like a hack.  
It should be merged but we should revisit it later
> making room for tab buttons by adjusting top css of map in FindRequests

- web-client/src/modules/phone/components/PhoneNumberEntryForm/PhoneNumberEntryForm.tsx
- web-client/src/translations/en.json
fixes 
(1) country letters in dial prefix 
(2) google autocomplete country  
(3) restores live feedback for form -- phone number is validated while entering it in the form.
(4) form is validated on submission
> Phone Fixes

- web-client/src/modules/requests/components/RequestItem/RequestItem.tsx
Modified key to point to correct json key and output the correct value.
> Issue#919 - Modify key to show correct output

- web-client/src/components/DashboardLayout/DashboardLayout.tsx
- web-client/src/components/NotificationsDrawer/NotificationsDrawer.tsx
- web-client/src/components/TopNavbar/TopNavbar.tsx
- web-client/src/components/__tests__/TopNavbar.test.tsx
- web-client/src/pages/MasterPage.tsx
This basically moves the buttons and their functionality to the TopNavbar and removes the BottomNavbar from the DashboardLayout component. This relates to #905 - 1st step
I think this can be merged right away without having to wait on the other changes related to this issue.
Also, @ashwinkjoseph should I write tests for these components before merging?
closes #924 
The other developers that are working on this issue, for reference
@gilwong, @vignesh-manel 
Video of it working (Slack) - https://reach4help.slack.com/archives/C0108KGNUL9/p1597771446338700
> Adds buttons to TopNavbar and removes the Bottom bar

- web-client/docs/CodingConventions/CONTRIBUTING.md
> fix: broken link to env.example

- web-client/src/components/AddressChooser/AddressChooser.tsx
- web-client/src/modules/landing-page/constants.tsx
- web-client/src/modules/landing-page/index.ts
- web-client/src/modules/settings/components/ChangeAddresses/ChangeAddresses.tsx
- web-client/src/pages/MasterPage.tsx
This fixes form issues and an issue where the landing page module was gobbling up routes, showing a blank page.
> Fix routing and update imports

- site/src/components/button/index.js
- web-client/src/components/BottomLinks/BottomLinks.tsx
- web-client/src/components/DashboardLayout/DashboardLayout.tsx
- web-client/src/components/GradientBackground/GradientBackground.tsx
- web-client/src/components/IntroComponent/IntroComponent.tsx
- web-client/src/components/LoadingComponent/LoadingComponent.tsx
- web-client/src/components/MenuDrawer/MenuDrawer.tsx
- web-client/src/components/Modals/EventTriggeredModal.tsx
- web-client/src/components/TitleWithOrangeUnderline/TitleWithOrangeUnderline.tsx
- web-client/src/components/WebClientMap/CustomMapControlPortal.tsx
- web-client/src/components/WebClientMap/utils.tsx
- web-client/src/components/figma/Modal.tsx
- web-client/src/ducks/requests/actions.ts
- web-client/src/ducks/requests/functions.ts
- web-client/src/modules/create/constants.tsx
- web-client/src/modules/create/routes.tsx
- web-client/src/modules/requests/constants.tsx
- web-client/src/modules/requests/pages/TabbedPostsPage.tsx
- web-client/src/modules/requests/routes.tsx
- web-client/src/modules/timeline/containers/TimelineViewContainer/TimelineViewContainer.tsx
- web-client/src/pages/MasterPage.tsx
- web-client/src/types/module.d.ts
Changed <Route> to <ProtectedRoute>.  This is easier to read than the way it is done in MasterPage.tsx.
> Bug 1015 protect my offer request create ethan

- web-client/src/components/WebClientMap/utils.tsx
Co-authored-by:  @Tapudp <divyeshpar2496@gmail.com>
Refactored utils.tsx to make it more obvious that there may be no addresses and what will be done if there are.  Paired with Divyesh on this and both of us found the new version easier to read.
> refactor: utils.tsx

- web-client/src/modules/create/components/PostReview.test.tsx
This is the outcome of last nights mob-programming session. It's always surprising how fast 2 hours pass.
After getting an overview of the project, we started with writing a first basic test for the existing PostReview component.
Can we leave the PR open in case someone wants to continue with that task?
Co-Authored-By: Joseph Ashwin Kottapurath <ashwinkjoseph@gmail.com>
Co-Authored-By: Dimitry Polivaev <dpolivaev@users.noreply.github.com>
Co-Authored-By: Daniel Bartholomae <daniel@bartholomae.name>
Co-Authored-By: Ethan-Strominger <32078396+ethanstrominger@users.noreply.github.com>
Co-Authored-By: Harald Reingruber <haraldreingruber@users.noreply.github.com>
Co-Authored-By: iuriihub <iuriihub@users.noreply.github.com>
Co-Authored-By: lombad <lombad@users.noreply.github.com>
This PR …
> WIP: 2.1.4 Extract ReviewPage global component

- web-client/src/components/AddressChooser/AddressChooser.tsx
- yarn.lock
> improvement: adds onChangeHandler to AddressChooser
